import string as st
ls= " This Is VEERA sharma"
print(ls.capitalize())
print(ls.upper())
print(ls.lower())
print(ls.center(3))
print(ls.count("a"))
print(ls.encode())
print(ls.endswith("a"))
print(ls.find("a"))
print(ls.expandtabs())
print(ls.format())
print(ls.format_map("None"))
print( ls.index("a"))
print(ls.isalnum())
print(ls.isalpha())
print(ls.isprintable())
print(ls.isspace())
print(ls.join('lokedh'))
print(ls.lstrip())