import math 
import keyword
print(math.__delattr__,'\n')
print(math.__class__,'\n')
print(math.__dict__,'\n')
print(math.__format__,'\n')
print(math.__getattribute__,'\n')
print(math.__hash__,'\n')
print(math.__init__,'\n')
#print(math.__module__,'\n')
print(math.__new__,'\n')
print(math.__reduce__,'\n')
print(math.__reduce_ex__,'\n')
print(math.__repr__,'\n')
print(math.__setattr__,'\n')
print(math.__sizeof__,'\n')
print(math.__str__,'\n')
print(math.__subclasshook__,'\n')
#print(math.__weakref__,'\n')